import CLMDB

// marker protocol for environment CORES: any struct generated by
// `@MDB_environment` (which owns exactly `env` + `Database.X` tables) conforms.
// the boundary dialect (`@MDB_transact`, `environments:` variadic) keys its
// environment inventory off this conformance.

public protocol MDB_environment {
	/// the environment handle for this core.
	var env: Environment { get }
}
