import CLMDB

// marker protocol for environment CORES: any struct generated by
// `@MDB_environment` (which owns exactly `env` + `Database.X` tables) conforms.
// the span-boundary machinery (`@MDB_app` containers + `@MDB_transact_span`)
// keys its environment inventory off this conformance.
public protocol MDB_environment {
	/// the environment handle for this core.
	var env: Environment { get }
}

// a CONTAINER of one or more `MDB_environment` cores, declared with `@MDB_app`.
// the span boundary macro (`@MDB_transact_span`) uses the inventory to route
// verb calls to per-core transactions and to diagnose unknown core names.
public protocol MDB_environment_container {
	/// the stored-property names of every environment core in this container,
	/// in declaration order (each resolves to `<name>.env`).
	static var mdb_environment_property_names: [String] { get }
}
